# Hexo Configuration.
## Docs: https://hexo.io/docs/deployment.html
## Source: https://github.com/hexojs/hexo

# Site.
title: Exokit
subtitle: The WebXR Engine
description: "Native VR/AR/XR engine for JavaScript"
email:
language:
robots: all
blog_title: Blog

# Color for `<meta name="theme-color">`.
## https://html.spec.whatwg.org/multipage/semantics.html#meta-theme-color
## https://developers.google.com/web/fundamentals/design-and-ui/browser-customization/theme-color
theme_color: black

# URL.
## If your site is put in a sub-directory, set URL as `http://yoursite.com/child` and root as `/child/`.
url: https://exokit.org
root: /
permalink: blog/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
force_https: true

# Directory.
source_dir: src
public_dir: public

# Writing.
new_post_name: :title.md  # File name of new posts
default_layout: page
auto_spacing: false  # Add spaces between Asian characters and western characters.
titlecase: false  # Transform title into "title case."
external_link: true  # Open external links in a new tab.
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: false
highlight:
  enable: true
  line_number: false
  tab_replace:

# Category & Tag.
default_category: uncategorized
category_map:
tag_map:

# Archives.
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully disable
archive: 0
category: 0
tag: 0

# Server.
## Hexo uses Connect as a local development server.
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html.
server:
  port: 4000
  log: true

# Date / Time format
## Hexo uses Moment.js to parse and display dates.
## You can customise the date format as defined in
## http://momentjs.com/docs/#/displaying/format/.
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
## Set `per_page` to `0` to disable pagination.
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: exokit
exclude_generator:
- index

# Feed.
## Plugin: https://github.com/hexojs/hexo-generator-feed
feed:
  type: rss2
  path: feed.xml
  limit: 15
  hub:

# Markdown.
## https://github.com/chjj/marked
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: false
  smartLists: true
  smartypants: true
  modifyAnchors: 1   # Lowercased anchors.

# BrowserSync
## Repo: https://github.com/hexojs/hexo-browsersync
## Options: https://www.browsersync.io/docs/options/
browsersync:
  notify: false

# Deployment.
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:exokitxr/exokitxr-site.git
  branch: gh-pages

disqus_shortname:
twitter:
  username: exokitXR
  url: https://twitter.com/exokitXR/
instagram:
    username: exokitXR
    url: 'https://instagram.com/exokitXR/'
facebook:
    username: exokitXR
    url: 'https://facebook.com/exokitxr'
youtube:
    url: 'https://www.youtube.com/channel/UC87Q7_5ooY8FSLwOec52ZPQ'
twitch:
    url: 'https://www.twitch.tv/exokitXR'
mailinglist:
    url: 'http://eepurl.com/dFiLMz'
google_analytics:
google_analytics_mozilla_managers:
fb_app_id:

github:
  exokit:
    username: exokitxr
    repo: exokit
    url: https://github.com/exokitxr/exokit/
  exokit_site:
    username: exokitxr
    repo: exokit-site
    url: https://github.com/exokitxr/exokit-site/


exokit_lib:
  home_url: https://exokit.org/

slack:
  exokit:
    signup_url: https://exokit.slack.com/join/shared_invite/enQtNDI3NjcxNzYwMDIxLWU2NmFmOTEzMzk4NWNiYjRhMjVkYzcyNjg5YjUyMzZkYWM1ZGI4M2IwYWZiMjNlMTJjMDlkM2U3Y2JiNTc2M2Q

discord:
    exokit:
        url: 'https://discord.gg/wm62cFN'

reddit:
  webvr:
    url: https://www.reddit.com/r/webvr

stack_overflow:
  exokit:
    url: https://stackoverflow.com/questions/tagged/exokit
  webvr:
    url: https://stackoverflow.com/questions/tagged/webvr

exokit_version: master

# Enable the Single-Page App.
spa: false

css_minifier:
  enable: true

# Don't enable `minifyJS`, it breaks inline single JS quotes in HTML.
html_minifier:
  enable: false
  exclude:
  minifyJS: false

# Note: `exclude` option doesn't work.
js_minifier:
  enable: true

# Disabled because mozjpeg errors on OS X.
image_minifier:
  enable: false

keywords:
  - webvr
  - webvr framework
  - webvr demos
  - webvr sites
  - vr javascript
  - vr framework

githubEmojis:
  enable: true
  className: github-emoji
  unicode: false
  localEmojis:
